### PR TITLE
Path change

### PR DESCRIPTION
**Pull request by gorandev**
Changed path of the ZIP download.

### CODE REVIEW

**Comment by igoraj** [comment]
Tnx & sorry for the wait.

**Comment by gorandev** [comment]
No worries! Thank you for making the puppet module in the first place! :)

**Comment by igoraj** [comment]
@gorandev i've also finally uploaded it to forge as well, so if you prefer you can fetch it from there as well.

**Comment by gorandev** [comment]
What's this "forge" you're talking about? Sorry for asking but I have no clue!

**Pull request merged**
